//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffLogin
    {
        public int staffUserID { get; set; }
        public string staffUsername { get; set; }
        public string staffPassword { get; set; }
    }
}
